val parseNominalJson : string -> transaction (QuantityJson.parseResult Comp.nominal)
val parseCompInputJson : string -> transaction (QuantityJson.parseResult Comp.compInput)
val parseTasksJson : string -> transaction (QuantityJson.parseResult (list Comp.compTask))
val parseTaskLengthsJson : string -> transaction (QuantityJson.parseResult (list Comp.taskLength))
val parsePilotsJson : string -> transaction (QuantityJson.parseResult (list Comp.pilotStatus))
